repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
- repo: local
  hooks:
  - id: pytest
    language: system
    pass_filenames: false
    name: pytest
    entry: pytest
    types: [python]
- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [--max-line-length=120]
